import Header from '@/components/header';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ActiveSectionContextProvider from '@/context/activeSectionContext';
import { Toaster } from 'react-hot-toast';
import Footer from '@/components/footer';
import ThemeSwitch from '@/components/themeSwitch';
import ThemeContextProvider from '@/context/themeContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
   title: 'Juhandi Personal Portfolio',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang='en' className='!scroll-smooth'>
         <body
            className={`${inter.className} relative bg-gray-100 dark:bg-gray-900 dark:text-gray-50 dark:text-opacity-90 text-gray-950 pt-28 sm:pt-36`}
         >
            <div className='absolute bg-fuchsia-200 dark:bg-fuchsia-400 top-[-6rem] right-[11rem] -z-10 h-[31.2rem] w-[31.25rem] rounded-full blur-[10rem] dark:blur-[20rem] sm:w-[68.75rem]'></div>
            <div className='absolute bg-indigo-200 dark:bg-indigo-400 top-[-1rem] left-[-35rem] -z-10 h-[31.2rem] w-[50rem] rounded-full blur-[10rem] dark:blur-[20rem] sm:w-[68.75rem] md:left-[-33rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem]'></div>
            <ThemeContextProvider>
               <ActiveSectionContextProvider>
                  <Header />
                  {children}
                  <Footer />
                  <Toaster position='top-right' />
                  <ThemeSwitch />
               </ActiveSectionContextProvider>
            </ThemeContextProvider>
         </body>
      </html>
   );
}
